Comport:
  port:     "/dev/ttyACM0"
  baudrate: 115200
  dotino:   "./ino/proto.ino"
  warmup:   2.0


Experimental:
  # camera settings
  black-cam:        2
  white-cam:        4
  # bgr = List[uint8]
  black-bgr-min:    [30, 0, 0]
  black-bgr-max:    [255, 255, 100]
  white-bgr-min:    [80, 0, 0]
  white-bgr-max:    [255, 255, 140]
  black-threshold:  2
  white-threshold:  2
  # pin settings
  black-led:        5
  white-led:        7
  black-reward:     4
  white-reward:     6
  # experimental conditions
  black-interval:   10 # seconds
  white-interval:   10 # seconds
  balckout:         10 # seconds
  trial:            10
  session-duration: 2100 # seconds

Metadata:
  subject: g1c
  condition: conc-VI-90-90
