Comport:
  port:     "/dev/ttyACM0"
  baudrate: 115200
  dotino:   "./talloc/proto.ino"
  warmup:   2.0


Experimental:
  # camera settings
  left-cam:         2
  right-cam:        4
  # bgr = List[uint8]
  left-bgr-min:     [0, 0, 0]
  left-bgr-max:     [255, 255, 100]
  right-bgr-min:    [80, 0, 0]
  right-bgr-max:    [255, 255, 140]
  left-threshold:   2
  right-threshold:  2
  # pin settings
  left-led:         5
  right-led:        7
  left-reward:      4
  right-reward:     6
  # experimental conditions
  left-interval:    90 # seconds
  right-interval:   90 # seconds
  balckout:         10 # seconds
  trial:            40
  session-duration: 2100 # seconds

Metadata:
  subject: g1c
  condition: conc-VI-90-90
